CREATE DATABASE IF NOT EXISTS ChefsDiary;

CREATE TABLE IF NOT EXISTS User (
    IdUser INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Login VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    RefreshToken VARCHAR(255) DEFAULT NULL,
    IsDisabled BIT NOT NULL DEFAULT 0,
    LoginRestrictedUntil DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS UserInfo (
    IdUserInfo INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	IdUser INT UNSIGNED NOT NULL,
	UserName VARCHAR(50) DEFAULT NULL,
    Email VARCHAR(50) DEFAULT NULL,
    Phone VARCHAR(50) DEFAULT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    INDEX idx_UserInfo__IdUser (IdUser),
    FOREIGN KEY fx_UserInfo__IdUser (IdUser)
        REFERENCES User (IdUser)
);